# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 895ccbab94a81340ee6ff74e0b4ae41883851977a7aedee6f5d4865602d47f6ff79d7fe657c268032aab81afa7b744c0e7411913aed9dbf6db53983dc6de3711

test:
  secret_key_base: cbcea6870bfba5221a9aba1c518b493b3e96d2e992c0c202f743656eec5f5ffdbd8084288c392674f8a6dc7b7c4c289a7ba70840f1b2540193c35cb7629ccabb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
